{
 "title": "Weather Station",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(weather_tempf{id=\"KMAFRAMI83\"})*1000"
    }
   ]
  },
  {
   "title": "Daily",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(sum(weather_tempf{})[24h:1h])",
     "legendFormat": "Low"
    },
    {
     "expr": "max_over_time(sum(weather_tempf{})[24h:1h])",
     "legendFormat": "High"
    },
    { "expr": "weather_dailyrainin", "legendFormat": "Precipitation" }
   ]
  },
  {
   "title": "Current Conditions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_tempf", "legendFormat": "Temperature" },
    { "expr": "weather_dewptf", "legendFormat": "Dew Point" }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_baromin" }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_humidity", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "Wind",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_windspeedmph", "legendFormat": "Wind " },
    { "expr": "weather_windgustmph", "legendFormat": "Wind Gust" }
   ]
  },
  {
   "title": "Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    { "expr": "weather_tempf", "legendFormat": "Temp" },
    { "expr": "weather_dewptf", "legendFormat": "Dew Point" },
    { "expr": "weather_humidity", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "Percipation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "targets": [
    { "expr": "weather_rainin", "legendFormat": "Inches/hr" },
    { "expr": "weather_dailyrainin", "legendFormat": "inches/day" }
   ]
  },
  {
   "title": "Wind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    { "expr": "weather_windspeedmph{}", "legendFormat": "Speed" },
    { "expr": "weather_windgustmph", "legendFormat": "Gusts" }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    { "expr": "weather_winddir", "legendFormat": "Direction" }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "targets": [
    { "expr": "weather_baromin", "legendFormat": "inHg" }
   ]
  }
 ]
}